name: pre-merge
run-name: ${{ github.actor }} pre-merge checks
on: [pull_request]
jobs:
  linting:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install hatch
      - run: hatch run dev:lint
  test_examples:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install hatch
      - run: hatch run examples:morpho --seed 101
      - run: hatch run examples:morpho --seed 202
      - run: hatch run examples:morpho --seed 303
      - run: hatch run examples:morpho --seed 404
      - run: hatch run examples:morpho --seed 505
      - run: hatch run examples:morpho --seed 606
      - run: hatch run examples:morpho --seed 707
      - run: hatch run examples:morpho --seed 808
      - run: hatch run examples:morpho --seed 909
      - run: hatch run examples:morpho --seed 1010
